//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export function gql(strings: TemplateStringsArray, ...args: string[]): string {
  let str = "";
  strings.forEach((string, i) => {
    str += string + (args[i] || "");
  });
  return str;
}
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
export type MakeEmpty<
  T extends { [key: string]: unknown },
  K extends keyof T,
> = { [_ in K]?: never };
export type Incremental<T> =
  | T
  | {
      [P in keyof T]?: P extends " $fragmentName" | "__typename" ? T[P] : never;
    };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string };
  String: { input: string; output: string };
  Boolean: { input: boolean; output: boolean };
  Int: { input: number; output: number };
  Float: { input: number; output: number };
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any };
  JSON: { input: any; output: any };
};

export type SystemInfo = {
  __typename?: "SystemInfo";
  filename: Scalars["String"]["output"];
  title?: Maybe<Scalars["String"]["output"]>;
  basename: Scalars["String"]["output"];
  hasReferences?: Maybe<Scalars["Boolean"]["output"]>;
  breadcrumbs: Array<Scalars["String"]["output"]>;
  path: Scalars["String"]["output"];
  relativePath: Scalars["String"]["output"];
  extension: Scalars["String"]["output"];
  template: Scalars["String"]["output"];
  collection: Collection;
};

export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type Folder = {
  __typename?: "Folder";
  name: Scalars["String"]["output"];
  path: Scalars["String"]["output"];
};

export type PageInfo = {
  __typename?: "PageInfo";
  hasPreviousPage: Scalars["Boolean"]["output"];
  hasNextPage: Scalars["Boolean"]["output"];
  startCursor: Scalars["String"]["output"];
  endCursor: Scalars["String"]["output"];
};

export type Node = {
  id: Scalars["ID"]["output"];
};

export type Document = {
  id: Scalars["ID"]["output"];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars["JSON"]["output"];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars["Float"]["output"];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: "Query";
  getOptimizedQuery?: Maybe<Scalars["String"]["output"]>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pages_en: Pages_En;
  pages_enConnection: Pages_EnConnection;
  pages_es: Pages_Es;
  pages_esConnection: Pages_EsConnection;
};

export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars["String"]["input"];
};

export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryNodeArgs = {
  id?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryPages_EnArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryPages_EnConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<Pages_EnFilter>;
};

export type QueryPages_EsArgs = {
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type QueryPages_EsConnectionArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<Pages_EsFilter>;
};

export type DocumentFilter = {
  pages_en?: InputMaybe<Pages_EnFilter>;
  pages_es?: InputMaybe<Pages_EsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: "DocumentConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: "DocumentConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: "Collection";
  name: Scalars["String"]["output"];
  slug: Scalars["String"]["output"];
  label?: Maybe<Scalars["String"]["output"]>;
  path: Scalars["String"]["output"];
  format?: Maybe<Scalars["String"]["output"]>;
  matches?: Maybe<Scalars["String"]["output"]>;
  templates?: Maybe<Array<Maybe<Scalars["JSON"]["output"]>>>;
  fields?: Maybe<Array<Maybe<Scalars["JSON"]["output"]>>>;
  documents: DocumentConnection;
};

export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars["String"]["input"]>;
};

export type DocumentNode = Pages_En | Pages_Es | Folder;

export type Pages_En = Node &
  Document & {
    __typename?: "Pages_en";
    title: Scalars["String"]["output"];
    description?: Maybe<Scalars["String"]["output"]>;
    locale?: Maybe<Scalars["String"]["output"]>;
    darkBackground?: Maybe<Scalars["Boolean"]["output"]>;
    body?: Maybe<Scalars["JSON"]["output"]>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type StringFilter = {
  startsWith?: InputMaybe<Scalars["String"]["input"]>;
  eq?: InputMaybe<Scalars["String"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
  in?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars["Boolean"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type Pages_EnBodyMenubarFilter = {
  locale?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars["String"]["input"]>;
  eq?: InputMaybe<Scalars["String"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
  in?: InputMaybe<Array<InputMaybe<Scalars["String"]["input"]>>>;
};

export type Pages_EnBodyImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  fill?: InputMaybe<BooleanFilter>;
  className?: InputMaybe<StringFilter>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars["String"]["input"]>;
  eq?: InputMaybe<Scalars["String"]["input"]>;
  exists?: InputMaybe<Scalars["Boolean"]["input"]>;
};

export type Pages_EnBodyAlertFilter = {
  children?: InputMaybe<RichTextFilter>;
};

export type Pages_EnBodyCardFilter = {
  children?: InputMaybe<RichTextFilter>;
};

export type Pages_EnBodyTrackedAirbnbButtonFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type Pages_EnBodyFilter = {
  Menubar?: InputMaybe<Pages_EnBodyMenubarFilter>;
  Image?: InputMaybe<Pages_EnBodyImageFilter>;
  Alert?: InputMaybe<Pages_EnBodyAlertFilter>;
  Card?: InputMaybe<Pages_EnBodyCardFilter>;
  TrackedAirbnbButton?: InputMaybe<Pages_EnBodyTrackedAirbnbButtonFilter>;
};

export type Pages_EnFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  darkBackground?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<Pages_EnBodyFilter>;
};

export type Pages_EnConnectionEdges = {
  __typename?: "Pages_enConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<Pages_En>;
};

export type Pages_EnConnection = Connection & {
  __typename?: "Pages_enConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<Pages_EnConnectionEdges>>>;
};

export type Pages_Es = Node &
  Document & {
    __typename?: "Pages_es";
    title: Scalars["String"]["output"];
    description?: Maybe<Scalars["String"]["output"]>;
    locale?: Maybe<Scalars["String"]["output"]>;
    darkBackground?: Maybe<Scalars["Boolean"]["output"]>;
    body?: Maybe<Scalars["JSON"]["output"]>;
    id: Scalars["ID"]["output"];
    _sys: SystemInfo;
    _values: Scalars["JSON"]["output"];
  };

export type Pages_EsBodyMenubarFilter = {
  locale?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyImageFilter = {
  src?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  fill?: InputMaybe<BooleanFilter>;
  className?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyAlertFilter = {
  children?: InputMaybe<RichTextFilter>;
};

export type Pages_EsBodyCardFilter = {
  children?: InputMaybe<RichTextFilter>;
};

export type Pages_EsBodyTrackedAirbnbButtonFilter = {
  href?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type Pages_EsBodyFilter = {
  Menubar?: InputMaybe<Pages_EsBodyMenubarFilter>;
  Image?: InputMaybe<Pages_EsBodyImageFilter>;
  Alert?: InputMaybe<Pages_EsBodyAlertFilter>;
  Card?: InputMaybe<Pages_EsBodyCardFilter>;
  TrackedAirbnbButton?: InputMaybe<Pages_EsBodyTrackedAirbnbButtonFilter>;
};

export type Pages_EsFilter = {
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  locale?: InputMaybe<StringFilter>;
  darkBackground?: InputMaybe<BooleanFilter>;
  body?: InputMaybe<Pages_EsBodyFilter>;
};

export type Pages_EsConnectionEdges = {
  __typename?: "Pages_esConnectionEdges";
  cursor: Scalars["String"]["output"];
  node?: Maybe<Pages_Es>;
};

export type Pages_EsConnection = Connection & {
  __typename?: "Pages_esConnection";
  pageInfo: PageInfo;
  totalCount: Scalars["Float"]["output"];
  edges?: Maybe<Array<Maybe<Pages_EsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: "Mutation";
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePages_en: Pages_En;
  createPages_en: Pages_En;
  updatePages_es: Pages_Es;
  createPages_es: Pages_Es;
};

export type MutationAddPendingDocumentArgs = {
  collection: Scalars["String"]["input"];
  relativePath: Scalars["String"]["input"];
  template?: InputMaybe<Scalars["String"]["input"]>;
};

export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
  params: DocumentUpdateMutation;
};

export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
};

export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
  params: DocumentMutation;
};

export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars["String"]["input"]>;
  relativePath: Scalars["String"]["input"];
};

export type MutationUpdatePages_EnArgs = {
  relativePath: Scalars["String"]["input"];
  params: Pages_EnMutation;
};

export type MutationCreatePages_EnArgs = {
  relativePath: Scalars["String"]["input"];
  params: Pages_EnMutation;
};

export type MutationUpdatePages_EsArgs = {
  relativePath: Scalars["String"]["input"];
  params: Pages_EsMutation;
};

export type MutationCreatePages_EsArgs = {
  relativePath: Scalars["String"]["input"];
  params: Pages_EsMutation;
};

export type DocumentUpdateMutation = {
  pages_en?: InputMaybe<Pages_EnMutation>;
  pages_es?: InputMaybe<Pages_EsMutation>;
  relativePath?: InputMaybe<Scalars["String"]["input"]>;
};

export type DocumentMutation = {
  pages_en?: InputMaybe<Pages_EnMutation>;
  pages_es?: InputMaybe<Pages_EsMutation>;
};

export type Pages_EnMutation = {
  title?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  locale?: InputMaybe<Scalars["String"]["input"]>;
  darkBackground?: InputMaybe<Scalars["Boolean"]["input"]>;
  body?: InputMaybe<Scalars["JSON"]["input"]>;
};

export type Pages_EsMutation = {
  title?: InputMaybe<Scalars["String"]["input"]>;
  description?: InputMaybe<Scalars["String"]["input"]>;
  locale?: InputMaybe<Scalars["String"]["input"]>;
  darkBackground?: InputMaybe<Scalars["Boolean"]["input"]>;
  body?: InputMaybe<Scalars["JSON"]["input"]>;
};

export type Pages_EnPartsFragment = {
  __typename: "Pages_en";
  title: string;
  description?: string | null;
  locale?: string | null;
  darkBackground?: boolean | null;
  body?: any | null;
};

export type Pages_EsPartsFragment = {
  __typename: "Pages_es";
  title: string;
  description?: string | null;
  locale?: string | null;
  darkBackground?: boolean | null;
  body?: any | null;
};

export type Pages_EnQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type Pages_EnQuery = {
  __typename?: "Query";
  pages_en: {
    __typename: "Pages_en";
    id: string;
    title: string;
    description?: string | null;
    locale?: string | null;
    darkBackground?: boolean | null;
    body?: any | null;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
  };
};

export type Pages_EnConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<Pages_EnFilter>;
}>;

export type Pages_EnConnectionQuery = {
  __typename?: "Query";
  pages_enConnection: {
    __typename?: "Pages_enConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "Pages_enConnectionEdges";
      cursor: string;
      node?: {
        __typename: "Pages_en";
        id: string;
        title: string;
        description?: string | null;
        locale?: string | null;
        darkBackground?: boolean | null;
        body?: any | null;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
      } | null;
    } | null> | null;
  };
};

export type Pages_EsQueryVariables = Exact<{
  relativePath: Scalars["String"]["input"];
}>;

export type Pages_EsQuery = {
  __typename?: "Query";
  pages_es: {
    __typename: "Pages_es";
    id: string;
    title: string;
    description?: string | null;
    locale?: string | null;
    darkBackground?: boolean | null;
    body?: any | null;
    _sys: {
      __typename?: "SystemInfo";
      filename: string;
      basename: string;
      hasReferences?: boolean | null;
      breadcrumbs: Array<string>;
      path: string;
      relativePath: string;
      extension: string;
    };
  };
};

export type Pages_EsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars["String"]["input"]>;
  after?: InputMaybe<Scalars["String"]["input"]>;
  first?: InputMaybe<Scalars["Float"]["input"]>;
  last?: InputMaybe<Scalars["Float"]["input"]>;
  sort?: InputMaybe<Scalars["String"]["input"]>;
  filter?: InputMaybe<Pages_EsFilter>;
}>;

export type Pages_EsConnectionQuery = {
  __typename?: "Query";
  pages_esConnection: {
    __typename?: "Pages_esConnection";
    totalCount: number;
    pageInfo: {
      __typename?: "PageInfo";
      hasPreviousPage: boolean;
      hasNextPage: boolean;
      startCursor: string;
      endCursor: string;
    };
    edges?: Array<{
      __typename?: "Pages_esConnectionEdges";
      cursor: string;
      node?: {
        __typename: "Pages_es";
        id: string;
        title: string;
        description?: string | null;
        locale?: string | null;
        darkBackground?: boolean | null;
        body?: any | null;
        _sys: {
          __typename?: "SystemInfo";
          filename: string;
          basename: string;
          hasReferences?: boolean | null;
          breadcrumbs: Array<string>;
          path: string;
          relativePath: string;
          extension: string;
        };
      } | null;
    } | null> | null;
  };
};

export const Pages_EnPartsFragmentDoc = gql`
  fragment Pages_enParts on Pages_en {
    __typename
    title
    description
    locale
    darkBackground
    body
  }
`;
export const Pages_EsPartsFragmentDoc = gql`
  fragment Pages_esParts on Pages_es {
    __typename
    title
    description
    locale
    darkBackground
    body
  }
`;
export const Pages_EnDocument = gql`
  query pages_en($relativePath: String!) {
    pages_en(relativePath: $relativePath) {
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...Pages_enParts
    }
  }
  ${Pages_EnPartsFragmentDoc}
`;
export const Pages_EnConnectionDocument = gql`
  query pages_enConnection(
    $before: String
    $after: String
    $first: Float
    $last: Float
    $sort: String
    $filter: Pages_enFilter
  ) {
    pages_enConnection(
      before: $before
      after: $after
      first: $first
      last: $last
      sort: $sort
      filter: $filter
    ) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      totalCount
      edges {
        cursor
        node {
          ... on Document {
            _sys {
              filename
              basename
              hasReferences
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
          ...Pages_enParts
        }
      }
    }
  }
  ${Pages_EnPartsFragmentDoc}
`;
export const Pages_EsDocument = gql`
  query pages_es($relativePath: String!) {
    pages_es(relativePath: $relativePath) {
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
      ...Pages_esParts
    }
  }
  ${Pages_EsPartsFragmentDoc}
`;
export const Pages_EsConnectionDocument = gql`
  query pages_esConnection(
    $before: String
    $after: String
    $first: Float
    $last: Float
    $sort: String
    $filter: Pages_esFilter
  ) {
    pages_esConnection(
      before: $before
      after: $after
      first: $first
      last: $last
      sort: $sort
      filter: $filter
    ) {
      pageInfo {
        hasPreviousPage
        hasNextPage
        startCursor
        endCursor
      }
      totalCount
      edges {
        cursor
        node {
          ... on Document {
            _sys {
              filename
              basename
              hasReferences
              breadcrumbs
              path
              relativePath
              extension
            }
            id
          }
          ...Pages_esParts
        }
      }
    }
  }
  ${Pages_EsPartsFragmentDoc}
`;
export type Requester<C = {}> = <R, V>(
  doc: DocumentNode,
  vars?: V,
  options?: C,
) => Promise<R>;
export function getSdk<C>(requester: Requester<C>) {
  return {
    pages_en(
      variables: Pages_EnQueryVariables,
      options?: C,
    ): Promise<{
      data: Pages_EnQuery;
      errors?: {
        message: string;
        locations: { line: number; column: number }[];
        path: string[];
      }[];
      variables: Pages_EnQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: Pages_EnQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: Pages_EnQueryVariables;
          query: string;
        },
        Pages_EnQueryVariables
      >(Pages_EnDocument, variables, options);
    },
    pages_enConnection(
      variables?: Pages_EnConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: Pages_EnConnectionQuery;
      errors?: {
        message: string;
        locations: { line: number; column: number }[];
        path: string[];
      }[];
      variables: Pages_EnConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: Pages_EnConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: Pages_EnConnectionQueryVariables;
          query: string;
        },
        Pages_EnConnectionQueryVariables
      >(Pages_EnConnectionDocument, variables, options);
    },
    pages_es(
      variables: Pages_EsQueryVariables,
      options?: C,
    ): Promise<{
      data: Pages_EsQuery;
      errors?: {
        message: string;
        locations: { line: number; column: number }[];
        path: string[];
      }[];
      variables: Pages_EsQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: Pages_EsQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: Pages_EsQueryVariables;
          query: string;
        },
        Pages_EsQueryVariables
      >(Pages_EsDocument, variables, options);
    },
    pages_esConnection(
      variables?: Pages_EsConnectionQueryVariables,
      options?: C,
    ): Promise<{
      data: Pages_EsConnectionQuery;
      errors?: {
        message: string;
        locations: { line: number; column: number }[];
        path: string[];
      }[];
      variables: Pages_EsConnectionQueryVariables;
      query: string;
    }> {
      return requester<
        {
          data: Pages_EsConnectionQuery;
          errors?: {
            message: string;
            locations: { line: number; column: number }[];
            path: string[];
          }[];
          variables: Pages_EsConnectionQueryVariables;
          query: string;
        },
        Pages_EsConnectionQueryVariables
      >(Pages_EsConnectionDocument, variables, options);
    },
  };
}
export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string;
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], "body" | "method">;
    },
    client,
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl;
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf("/");
      url = client.apiUrl.substring(0, index + 1) + options.branch;
    }
    const data = await client.request(
      {
        query: doc,
        variables: vars,
        url,
      },
      options,
    );

    return {
      data: data?.data,
      errors: data?.errors,
      query: doc,
      variables: vars || {},
    };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.1/content/88b70312-f5f7-4781-a2b4-f79704cc43bd/github/main",
        queries,
      }),
    ),
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};
